### ISSUE TITLE
Blank screen - init.js?1cbe:18 Uncaught TypeError: Cannot read property '_' of undefined - init.js

### ISSUE THREAD

**Issue by cbluth** [wailsapp/todo#9] opened 2020-11-14 11:54 UTC
i am trying to run this todo app locally.

here are my basic steps:
- git clone
- cd frontend ; npm install ; npm run build ; npm run serve
- then open in local browser, i get a blank screen:

 
![image](https://user-images.githubusercontent.com/6709636/99146441-7b360180-2678-11eb-9572-4d312042c2be.png)

**Comment by leaanthony** [comment] 2020-11-14 22:30
Hey there, yeah this repo is pretty old. There was a PR recently to fix it which was merged. Will check to see what's going on :+1:

**Comment by leaanthony** [comment] 2020-11-14 22:34
Linux + `wails build` = 
![image](https://user-images.githubusercontent.com/1943904/99158309-754a2a00-2725-11eb-8341-f20613cb7974.png)

Linux + `wails serve` + `npm run serve`:
![image](https://user-images.githubusercontent.com/1943904/99158328-a9254f80-2725-11eb-80f6-13b6ff9eacd1.png)

Can't reproduce I'm afraid.

**Closed** 2021-05-31 22:41 UTC
